[package]
name = "imaged"
version = "0.1.0"
authors = ["Zach Shipko <zachshipko@gmail.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/zshipko/imaged"
license = "ISC"

[dependencies]
halide-runtime = {git = "https://github.com/zshipko/halide-runtime", optional = true}
glfw = {version = "0.34", optional = true}
gl = {version = "0.14", optional = true}

[build-dependencies]
pkg-config = "0.3"

[features]
default = ["halide", "viewer"]
halide = ["halide-runtime"]
viewer = ["glfw", "gl"]
