[package]
name = "imaged"
version = "0.1.0"
authors = ["Zach Shipko <zachshipko@gmail.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/zshipko/imaged"
license = "ISC"

[package.metadata.docs.rs]
all-features = true

[dependencies]
thiserror = "1.0"
halide-runtime = {version = "0.2", optional = true}
glfw = {version = "0.36", optional = true}
gl = {version = "0.14", optional = true}

[build-dependencies]
pkg-config = "0.3"

[features]
default = ["halide"]
halide = ["halide-runtime"]
viewer = ["glfw", "gl"]
