name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install latest Rust nightly
      uses: actions-rs/toolchain@v1
      with:
            toolchain: nightly
            override: true
    - name: Dependencies
      run: sudo add-apt-repository ppa:longsleep/golang-backports && sudo apt-get update && sudo apt-get install git libtiff-dev libraw-dev libbabl-dev make check libsubunit-dev xorg-dev libglu1-mesa-dev
    - name: Build ezimage
      run: git clone https://github.com/zshipko/ezimage && cd ezimage && make && sudo make install
    - name: make
      run: make && sudo make install
    - name: make test
      run: make test
    - name: Rust
      run: cargo test
    - name: Go
      run: go build go/...
